services:
  jenkins:
    build: 
      context: .
    ports:
      - "2529:8080"
    volumes:
      - jenkins_home:/var/jenkins_home:rw
      - ./jcasc:/var/jenkins_home/jcasc-config-files:ro
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jcasc-config-files/
      - OIDC_ISSUER_URL=${OIDC_ISSUER_URL:-}
      - OIDC_PRIVATE_KEY_FILE=${OIDC_PRIVATE_KEY_FILE:-}
      - OIDC_PRIVATE_KEY=${OIDC_PRIVATE_KEY:-}
volumes:
  jenkins_home:
    name: jenkins_home
